language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
  - "pypy"
  - "pypy3"
sudo: false
install: pip install future coveralls
script: nosetests --with-coverage --cover-package=pyzufall --with-doctest
script: python setup.py install
after_success: coveralls
notifications:
  email:
    - post@davidak.de
