language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
# command to install dependencies
#install: "pip install -r requirements.txt"
install: pip install coveralls
# command to run tests
script: coverage run --source=pyzufall nosetests
after_success: coveralls
