language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
  - "pypy"
  - "pypy3"
sudo: false
install:
  - pip install -r requirements.txt
  # Coveralls 4.0 doesn't support Python 3.2
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.2" ]; then travis_retry pip install coverage==3.7.1; fi
  - if [ "$TRAVIS_PYTHON_VERSION" != "3.2" ]; then travis_retry pip install coverage; fi
script:
  - nosetests --with-coverage --cover-package=pyzufall --with-doctest
  - python setup.py install
after_success: coveralls
notifications:
  email:
    - post@davidak.de
